#Desde donde se va a iniciar el contenedor

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '80:80'

# Es mucho mas sofisticado y rapido que una maquina virtual
# Con volumes puedo enlazar el codigo para no tener que hacer cambios, entrar por medio de build y up cada vez